name: Mirror Codeberg → GitHub

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Codeberg repo as a mirror
        run: |
          git clone --mirror https://codeberg.org/MajorAmari/cpp-hw-fundamentals repo.git

      - name: Push mirror to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo.git
          git push --mirror https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
